apiVersion: v1
kind: Service
metadata:
  name: resume-backend
  labels:
    app: resume-backend
spec:
  selector:
    app: resume-backend
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: http
  type: ClusterIP
