apiVersion: v1
kind: Service
metadata:
  name: resume-frontend
  labels:
    app: resume-frontend
spec:
  selector:
    app: resume-frontend
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: http
  type: ClusterIP
